config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :media, only: %i[index create]
  root to: 'media#index'

  resources :movies
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/media_common.rb
# frozen_string_literal: true

module MediaCommon
  extend ActiveSupport::Concern

  included do
    def tmdb
      @tmdb ||= TmdbInstance.new(tmdb_id: tmdb_id)
    end

    # ["w92", "w154", "w185", "w342", "w500", "w780", "original"]
    def poster_url(size)
      # tmdb.configuration.poster_sizes
      base_url = tmdb.configuration.base_url
      "#{base_url}/#{size}#{poster_path}"
    end

    # ["w300", "w780", "w1280", "original"]
    def backdrop_url(size)
      # tmdb.configuration.backdrop_sizes
      base_url = tmdb.configuration.base_url
      "#{base_url}/#{size}#{backdrop_path}"
    end

    private

    def tmdb_images
      @tmdb_images ||= Tmdb::Movie.images(tmdb_id)
    end
  end

  # rubocop:disable Metrics/BlockLength
  class_methods do
    # rubocop:disable Metrics/AbcSize
    # rubocop:disable Metrics/MethodLength
    def sanitize(str)
      cleanstr = str.dup
      cleanstr.gsub!(/-\s*/, '')
      cleanstr.gsub!(/\[?1080p\]?/i, '')
      cleanstr.gsub!(/m?\[?720p\]?/i, '')
      cleanstr.gsub!(/\[[^\]]+\]/, '')
      cleanstr.gsub!(/ECI/, '')
      cleanstr.gsub!(/EXTENDED/, '')
      cleanstr.gsub!(/UNRATED/, '')
      cleanstr.gsub!(/ETRG/, '')
      cleanstr.gsub!(/VPPV/, '')
      cleanstr.gsub!(/HQ/, '')
      cleanstr.gsub!(/\.web\./i, '')
      cleanstr.gsub!(/\.us\./i, '')
      cleanstr.gsub!(/x264xlf/i, '')
      cleanstr.gsub!(/x264trump/i, '')
      cleanstr.gsub!(/x264/, '')
      cleanstr.gsub!(/AAC5?\.?1?/, '')
      cleanstr.gsub!(/[\.\s]B[dr]Rip[\.\s]/i, '')
      cleanstr.gsub!(/\.Br\./i, '')
      cleanstr.gsub!(/BluRay/i, '')
      cleanstr.gsub!(/BOKUTOX/i, '')
      cleanstr.gsub!(/GAZ/, '')
      cleanstr.gsub!(/HDTV/i, '')
      cleanstr.gsub!(/WEBRip/i, '')
      cleanstr.gsub!(/(Deceit)?\.?YIFY/, '')
      cleanstr.gsub!(/YTS\.AM/, '')
      cleanstr.gsub!(/-?xvid-?/i, '')
      cleanstr.gsub!(/-?maxspeed/i, '')
      cleanstr.gsub!(/www\.torentz\.3xforum\.ro\.avi/i, '')
      cleanstr.gsub!(/-lol/i, '')
      cleanstr.gsub!(/\+HI/i, '')
      cleanstr.gsub!(/muxed/i, '')
      cleanstr.gsub!(/\(dvd\)/i, '')
      cleanstr.gsub!(/dvdscr/i, '')
      cleanstr.gsub!(/mkv/i, '')
      cleanstr.gsub!(/aqos/i, '')
      cleanstr.gsub!(/ac3/i, '')
      cleanstr.gsub!(/hive/i, '')
      cleanstr.gsub!(/-?cm8/i, '')
      cleanstr.gsub!(/[\d\.]+mb/i, '')
      cleanstr.gsub!(/[\d\.]+gb/i, '')
      cleanstr.gsub!(/\s\s+/, ' ')
      cleanstr.tr!('_', ' ') # underscores
      cleanstr.gsub!(/[\.\+]/, ' ')
      cleanstr.strip!
      cleanstr
    end
    # rubocop:enable Metrics/MethodLength
    # rubocop:enable Metrics/AbcSize

    def basename(filepath)
      File.basename(filepath, extname(filepath))
    end

    def extname(filepath)
      File.extname(filepath)
    end

    def dirname(filepath)
      File.dirname(filepath)
    end
  end
  # rubocop:enable Metrics/BlockLength
end

app/models/movie.rb
# frozen_string_literal: true

class Movie < ApplicationRecord
  include MediaCommon

  after_initialize :initialize_tmdb

  validates :title, presence: true

  class << self
    # Determine if the passed file is most likely a Movie.
    # If it is, that usually means the file was named with movie title and
    # year somwehere in the filename
    #
    # @return [Boolean] TmdbInstance if likely a Movie, false if not
    def match?(filepath)
      base          = basename(filepath)
      possible_year = possible_year_in_title(base)
      clean_title   = sanitize(base).gsub(/[\s\.\-\_]\(?\d+\s*\)?$/, '')
      tmdb_instance = TmdbInstance.new(title: clean_title, year: possible_year)
      return tmdb_instance if tmdb_instance.movie?

      false
    end

    # Instantiate an instance based on the API call
    #
    # @param filepath [String] Path to the file on disk
    # @param tmdb_instance [TmdbInstance] An instance with at least one match
    # @return [Movie] An instance of Movie
    def instance(filepath, tmdb_instance)
      data = tmdb_instance.to_h
      data['tmdb_id'] = data.delete('id') # Rename the TMDB id
      exclude_attribs = data.keys - attribute_names
      create(data.except(*exclude_attribs).merge(filepath: filepath))
    rescue ActiveRecord::RecordNotUnique => _err
      # It is a duplicate so swallow it
    end

    private

    def possible_year_in_title(title)
      title_with_year = sanitize(title)
      md = title_with_year.match(/(\d{4}+)/)
      md ? md[1] : nil
    end
  end

  private

  def initialize_tmdb
    tmdb
  end
end

app/models/tv_show.rb
# frozen_string_literal: true

class TvShow < ApplicationRecord
  include MediaCommon

  S_E_EXPRESSIONS = [
    /(s(\d+)e(\d+))/i,
    /((\d+)x(\d+))/i
  ].freeze

  class << self
    def match?(filepath)
      index = nil
      clean_title = nil
      base = basename(filepath)
      sanitized = sanitize(base)
      S_E_EXPRESSIONS.each do |regex|
        next unless (md = sanitized.match(regex))

        index = sanitized.index(md[1], 0)
        clean_title = sanitized[0..index - 1].strip
        break
      end
      return false unless clean_title

      tmdb_instance = TmdbInstance.new(clean_title)
      return tmdb_instance if tmdb_instance.tv_show?

      false
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/media_controller.rb
# frozen_string_literal: true

class MediaController < ApplicationController
  def index
    @media_counts = {
      movies: Movie.count,
      tv_shows: TvShow.count
    }
  end

  def create
    count = 0
    list = MediaList.new([params[:path]])
    list.file_collection.each do |file|
      media = Medium.build_instance(file)
      if media.nil?
        Rails.logger.debug { "Skipping [#{file}]" }
        next
      end
      count += 1
    end
    redirect_to media_url
  end
end

app/controllers/movies_controller.rb
# frozen_string_literal: true

class MoviesController < ApplicationController
  before_action :set_movie, only: %i[show]

  def index
    @movies = Movie.paginate(page: params[:page])
  end

  def show
  end

  private

  def set_movie
    @movie = Movie.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/_flash.html.haml
- flash.each do |klass, msg|
  - if msg.respond_to?(:empty?)
    %div{ class: flash_classes(klass) }
      %button.delete
      = sanitize(msg)

app/views/layouts/_footer.html.haml
%footer.footer
  .container
    .content.has-text-centered
      .soc
        = image_tag('movie_icon.png')
        %p.title.pb-1
          Media Tools
      %p
        = link_to('Privacy Policy', root_path)
        |
        = link_to('About', root_path)
      %p
        Copyright &copy;
        = Time.zone.now.year
        Midwire Technologies LLC &middot; All Rights Reserved

app/views/layouts/_navigation.html.haml
%nav.navbar{"aria-label" => "main navigation", role: "navigation"}
  .container
    .navbar-brand
      %a.navbar-item{href: "/"}
        = image_tag('movie_icon.png')
        &nbsp;
        Media Tools
      %a.navbar-burger{"aria-expanded" => "false", "aria-label" => "menu", role: "button"}
        %span{"aria-hidden" => "true"}
        %span{"aria-hidden" => "true"}
        %span{"aria-hidden" => "true"}
    .navbar-menu
      .navbar-end
        .navbar-item
          = link_to('Home', '/')
        .navbar-item
          = link_to('About', root_path)
        -# - if user_signed_in?
        -#   .navbar-item.has-dropdown.is-hoverable
        -#     .navbar-link
        -#       = current_user.name
        -#     .navbar-dropdown
        -#       .navbar-item
        -#         %div
        -#           %span.icon.is-small
        -#             %i.fa.fa-user-circle-o
        -#           &nbsp;
        -#           = link_to("Profile", '/')
        -#       .navbar-item
        -#         %div
        -#           %span.icon.is-small
        -#             %i.fa.fa-sign-out
        -#           &nbsp;
        -#           = link_to("Sign Out", destroy_user_session_path, method: :delete)
        -# - else
        -#   .navbar-item
        -#     = link_to('Sign Up', new_user_registration_path)
        -#   .navbar-item
        -#     = link_to('Sign In', new_user_session_path)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}/
    %title Mediatools
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/navigation'
    = render 'layouts/flash'
    = yield
    = render 'layouts/footer'

app/views/media/index.html.haml
.section
  .container
    .content
      %h1 Welcome to Mediatools
      - if @media_counts[:movies] > 0 || @media_counts[:tv_shows] > 0
        %p You've got media!
        .columns
          .column
            .card
              .card-image
                %figure.image.is-4by3
                  %a{href: movies_path}
                    = image_tag('movies_logo.png')
              .card-content
                .content
                  %strong
                    Movies
                  = @media_counts[:movies]
          .column
            .card
              .card-image
                %figure.image.is-4by3
                  = image_tag('tv_logo.png')
              .card-content
                .content
                  %strong
                    TV Shows
                  = @media_counts[:tv_shows]
      - else
        %p You don't have any media yet.

      = form_tag(media_path, method: :post) do
        .field
          = label_tag(:path, 'Media Path', class: 'label')
          .control
            = text_field_tag(:path, 'Enter the root path to your media files', class: 'input')
        .field
          .control
            = submit_tag('Add Media Files', class: 'button is-primary')

app/views/movies/index.html.haml
.container
  .row.columns.is-multiline
    - @movies.find_each(batch_size: 6) do |movie|
      .column.is-one-quarter
        .box
          %a{href: movie_path(movie)}
            .card
              .card-image
                %figure.image.is-3by4
                  = image_tag(movie.poster_url('w154'))
              .card-content
                .media
                  .media-left
                    %figure.image.is-30x30
                      = image_tag('star.png')
                  .media-content
                    %p= movie.popularity
                .content
                  %p.title.is-6= movie.title

  = will_paginate(@movies)

app/views/movies/show.html.haml
.section.has-bg-image{'data-image' => @movie.backdrop_url('w1280')}
  .container
    .columns.is-mobile
      .column.is-one-third
        .card
          .card-image
            %figure.image
              = image_tag(@movie.poster_url('w342'))
      .column.has-tinted-background
        .content
          .title
            = @movie.title

          .level
            .level-left
              .level-item
                Released:
                = @movie.release_date
            .level-right
              .level-item
                Score:
                = @movie.vote_average

          %p
            = @movie.overview